USE DATAMART;
GO

IF OBJECT_ID('DBO.HANDSHK_ALUMNI_LOAD_LOG') IS NOT NULL
    DROP TABLE DBO.HANDSHK_ALUMNI_LOAD_LOG;
GO

CREATE TABLE DBO.HANDSHK_ALUMNI_LOAD_LOG (
    LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
    PREV_TERM_CD VARCHAR(6) NOT NULL,
    CURR_TERM_CD VARCHAR(6) NOT NULL,
    EXECUTION_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    ROW_COUNT INT DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'SUCCESS',   -- or FAILED if needed later
    MESSAGE NVARCHAR(1000) NULL,
);
GO
