USE [DATAMART]
GO

CREATE TABLE [dbo].[HANDSHK_CURRENT_STUDENTS_PREV_RUN_BACKUP](
	[email_address] [varchar](100) NULL,
	[username] [varchar](50) NULL,
	[auth_identifier] [varchar](100) NULL,
	[card_id] [varchar](50) NULL,
	[first_name] [varchar](50) NULL,
	[last_name] [varchar](50) NULL,
	[middle_name] [varchar](50) NULL,
	[preferred_name] [varchar](50) NULL,
	[school_year_name] [varchar](50) NULL,
	[primary_education_education_level_name] [varchar](50) NULL,
	[primary_education_cumulative_gpa] [decimal](10, 2) NULL,
	[primary_education_department_gpa] [decimal](10, 2) NULL,
	[primary_education_primary_major_name] [varchar](100) NULL,
	[primary_education_major_names] [varchar](max) NULL,
	[primary_education_minor_names] [varchar](max) NULL,
	[primary_education_college_name] [varchar](100) NULL,
	[primary_education_start_date] [varchar](50) NULL,
	[primary_education_end_date] [varchar](50) NULL,
	[primary_education_currently_attending] [varchar](50) NULL,
	[campus_name] [varchar](50) NULL,
	[opt_cpt_eligible] [varchar](50) NULL,
	[ethnicity] [varchar](50) NULL,
	[gender] [varchar](20) NULL,
	[disabled] [varchar](50) NULL,
	[work_study_eligible] [varchar](50) NULL,
	[system_label_names] [varchar](100) NULL,
	[mobile_number] [varchar](50) NULL,
	[assigned_to_email_address] [varchar](100) NULL,
	[hometown_location_name] [varchar](100) NULL,
	[athlete] [varchar](50) NULL,
	[first_generation] [varchar](50) NULL,
	[veteran] [varchar](50) NULL,
	[eu_gdpr_subject] [varchar](50) NULL,
	[row_hash] [char](64) NULL
)

CREATE TABLE [dbo].[HANDSHK_CURRENT_STUDENTS_PREV_RUN](
	[email_address] [varchar](100) NULL,
	[username] [varchar](50) NULL,
	[auth_identifier] [varchar](100) NULL,
	[card_id] [varchar](50) NULL,
	[first_name] [varchar](50) NULL,
	[last_name] [varchar](50) NULL,
	[middle_name] [varchar](50) NULL,
	[preferred_name] [varchar](50) NULL,
	[school_year_name] [varchar](50) NULL,
	[primary_education_education_level_name] [varchar](50) NULL,
	[primary_education_cumulative_gpa] [decimal](10, 2) NULL,
	[primary_education_department_gpa] [decimal](10, 2) NULL,
	[primary_education_primary_major_name] [varchar](100) NULL,
	[primary_education_major_names] [varchar](max) NULL,
	[primary_education_minor_names] [varchar](max) NULL,
	[primary_education_college_name] [varchar](100) NULL,
	[primary_education_start_date] [varchar](50) NULL,
	[primary_education_end_date] [varchar](50) NULL,
	[primary_education_currently_attending] [varchar](50) NULL,
	[campus_name] [varchar](50) NULL,
	[opt_cpt_eligible] [varchar](50) NULL,
	[ethnicity] [varchar](50) NULL,
	[gender] [varchar](20) NULL,
	[disabled] [varchar](50) NULL,
	[work_study_eligible] [varchar](50) NULL,
	[system_label_names] [varchar](100) NULL,
	[mobile_number] [varchar](50) NULL,
	[assigned_to_email_address] [varchar](100) NULL,
	[hometown_location_name] [varchar](100) NULL,
	[athlete] [varchar](50) NULL,
	[first_generation] [varchar](50) NULL,
	[veteran] [varchar](50) NULL,
	[eu_gdpr_subject] [varchar](50) NULL,
	[row_hash] [char](64) NULL
)


CREATE TABLE [dbo].[HANDSHK_CURRENT_STUDENTS_DELTA](
	[email_address] [varchar](100) NULL,
	[username] [varchar](50) NULL,
	[auth_identifier] [varchar](100) NULL,
	[card_id] [varchar](50) NULL,
	[first_name] [varchar](50) NULL,
	[last_name] [varchar](50) NULL,
	[middle_name] [varchar](50) NULL,
	[preferred_name] [varchar](50) NULL,
	[school_year_name] [varchar](50) NULL,
	[primary_education_education_level_name] [varchar](50) NULL,
	[primary_education_cumulative_gpa] [decimal](10, 2) NULL,
	[primary_education_department_gpa] [decimal](10, 2) NULL,
	[primary_education_primary_major_name] [varchar](100) NULL,
	[primary_education_major_names] [varchar](max) NULL,
	[primary_education_minor_names] [varchar](max) NULL,
	[primary_education_college_name] [varchar](100) NULL,
	[primary_education_start_date] [varchar](50) NULL,
	[primary_education_end_date] [varchar](50) NULL,
	[primary_education_currently_attending] [varchar](50) NULL,
	[campus_name] [varchar](50) NULL,
	[opt_cpt_eligible] [varchar](50) NULL,
	[ethnicity] [varchar](50) NULL,
	[gender] [varchar](20) NULL,
	[disabled] [varchar](50) NULL,
	[work_study_eligible] [varchar](50) NULL,
	[system_label_names] [varchar](100) NULL,
	[mobile_number] [varchar](50) NULL,
	[assigned_to_email_address] [varchar](100) NULL,
	[hometown_location_name] [varchar](100) NULL,
	[athlete] [varchar](50) NULL,
	[first_generation] [varchar](50) NULL,
	[veteran] [varchar](50) NULL,
	[eu_gdpr_subject] [varchar](50) NULL
) 

CREATE TABLE [dbo].[HANDSHK_CURRENT_STUDENTS_RUN_LOG] (
    [run_id] [int] IDENTITY(1,1) NOT NULL,
	[last_execution_date] [date] NOT NULL,
	[run_type] [varchar](20) NOT NULL,
	[newly_added_rows] [int] NULL,
	[total_rows] [int] NULL,
);



